### ISSUE TITLE
Crashing on particular odd playlists

### ISSUE THREAD

**Issue by pavelkomarov** [pavelkomarov/exportify#10]
Discovered by @shape55. spotify:playlist:53eljwwaQQhi93Zbet44si is an example. There is a song in there called Walk Alone that for some reason comes back as mostly empty JSON. If I intentionally add this song to a different playlist and export that one, I see the song's JSON comes back filled.

Makes no sense. Somehow the playlist itself is corrupted. Spotify's client must have some workaround, because the song shows up fine there. I need to at least catch these cases so the app doesn't crash.

Please post the URIs or links for playlists that just cause the button to spin forever, indicating a crash, in this thread. There are many ways things could potentially go wrong, so I foresee getting a lot of mileage out of this one.

**Comment by shape55** [comment]
Following up from your last comment on [#6](https://github.com/pavelkomarov/exportify/issues/6#issuecomment-508307983), I had no idea the Export All option was supposed to export the playlists only on that page.  Afaik, on the other forks it was supposed to export all playlists, but I never got it to work b/c I always had more than 50, and therefore always got the rate-limiting error.  

So I tried exporting all 20 on the first page, and you were correct.  The 19th one, which is my Local Files Playlist, won't export even though it exports fine on the other 3 Exportify forks I linked.  And it also gives me the "undefined exportify.js:260:29" error.  If I try Export All on the 2nd page it works and downloads a zip with those 20 playlists.

**Comment by pavelkomarov** [comment]
Post a link to the Local Files playlist so I can follow it and try to export it

**Comment by shape55** [comment]
Yes, forgot :)  spotify:playlist:6Ti1vmdDtuXWNHtkUDKIni

**Comment by pavelkomarov** [comment]
Update: The app now uses a try/catch construction to avoid crashing on problematic playlists and let the user know what's going on.

**Comment by shape55** [comment]
I tested it out again and the Export Group is able to bypass the problematic Local Files Playlist.  It now gives me this error at the top:

Couldn't export Local Files Playlist. Encountered TypeError: features[i] is undefined.

However, there was one playlist that did not export to the zip file the first time I tried, yet it was able to export fine by itself.  When I tried Export Group again though it included this one in the zip file.  This is it here: spotify:playlist:2Zp7lFi6zoWRldxMfXOHRp

**Comment by pavelkomarov** [comment]
You sure about that? There should be absolutely no difference between how a playlist behaves when it's exported alone vs as part of a group, because the group functionality loops through the list and calls the same function that gets called when you hit the export button for a particular list. [for loop near line 169](https://github.com/pavelkomarov/exportify/blob/master/exportify.js)

**Comment by shape55** [comment]
Yes, for sure – I actually still have the original zip file if you want me to upload it or take a screenshot.  There are 18 items in that first one, and 19 in the 2nd zip I exported, but there should have been 19 for both based on what you're saying.

**Comment by shape55** [comment]
spotify:playlist:38VEWhMUWGLO7JRLU6K64k (this is another local files playlist)
spotify:playlist:2GZIwHEvxvCCuO1EkAkOLP
spotify:playlist:37i9dQZF1DXdbXrPNafg9d

The first 2, as well as the default Local Files Playlist (spotify:playlist:2Zp7lFi6zoWRldxMfXOHRp) I reported before, export fine using [watsonbox's fork](https://rawgit.com/watsonbox/exportify/master/exportify.html), but the 3rd one does not.

**Comment by ethanmarston** [comment]
https://open.spotify.com/playlist/2wZoUNmmQKTCFlULmDYJMw?si=aWkA9x7dR8iXFYt22brqlw
 Reviving this thread for sum help 👍

**Comment by pavel-aicradle** [comment]
Did my try-catch catch the error at least?

**Comment by donniesticks** [comment]
Excuse my base explanation as I'm just a user...
I don't know if this is helpful, but I came here last night because I was getting a "features[i] is undefined" error. After some trial and error to no avail, I used the watsonbox version and it worked w/no modifications to the playlist. Given that watsonbox doesn't pull local file lines, I noticed that one local artist in my playlist was listed and had a release date of "null". She has an album coming out this Friday, which means she's in the Spotify db and it pulled her album. 
I deleted her song from the playlist, then came back to this Exportify and tried it again, and didn't get an error.

**Comment by pavelkomarov** [comment]
That's some really useful detective work! I'm not positive I'm going to fix my version any time soon, because watsonbox's reappearance and subsequent coding tear resulted in probably a more mature version than this one. But thank you all the same.

**Comment by dub4u** [comment]
Getting `TypeError: song.track is null` on `spotify:playlist:3GwtY1dcep9iJ2ZcKC97XW`

**Comment by ianlevesque** [comment]
Couldn't export Daily Drive with id 37i9dQZF1EfH7lWo5rmJIa. Encountered TypeError: Cannot read property 'id' of null.
Couldn't export The Beatles Abbey Road Experience with id 37i9dQZF1DX82uM9F4qTjN. Encountered TypeError: Cannot read property 'id' of null.
Couldn't export Alfred Playlist with id 0Kii4SxELdIAuYeB2p13R4. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Alprazolam with id 7cWr2cw0QJL7z5tVMWCTSQ. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Beach House Essentials with id 2h8QQ2fHE20S4RADHXSIcZ. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Ben Gibbard Essentials with id 43IXUXaDvWUhODYkqjQNl6. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Best of Guild Wars 2 with id 1LHeOo4ZGUCfv0DdKeeKws. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export blink-182 Essentials with id 25PDAnEdqFBuQguAQcb0LS. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Caffeine with id 4RxKt2ae2yzjNfZvgtAYlY. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Caffeine 2 with id 6gRXHQavZe7jgT4xGNlGVI. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Frozen with id 0OOiFhDSAPszVlYtPGT3lj. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Good Music from Strange Places with id 4ceZHSVXD4XILFaBY16dQa. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Green Day Essentials with id 07Hki8EkQQgUoSSSUoxNvf. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Green Day: Next Steps with id 70jNiEYl8VtWCMJCz8xWoj. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Indie Hits: 2009 with id 2XaVieihNScBrfsEJRNKhY. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Inspired by Stereolab with id 7b4LMEWCtoWv24WbnQZKaP. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Inspired by The Postal Service with id 40hQZJx6E7ALkCdRYUkBzK. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Killer Codas with id 3jfwvEg5UgZAZH6Uw2OyRp. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Kurt Vile Essentials with id 1FgVft3ikldeuHBXUCYaQW. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Matt and Kim Essentials with id 2XkojLBas0aMmRIlxx409I. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Matt Pond PA Essentials with id 4Rz0ewlQn0vI9ZB43CHdRv. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Motivation with id 3CdDBoUv51HHZnnioNiJ1b. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Recent & Nifty with id 10xGC3nnhm1FKlxw67VQPR. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Rilo Kiley Essentials with id 7t0wFmOxYO6nvYovlptfkT. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Stars Essentials with id 79UZMlXJo3bB5k54j4RbyP. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Stereolab Essentials with id 03ZZEOrzp54Qi3RfTtQUIy. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Sufjan Stevens Essentials with id 4UrFwxmPHpC0I7BkxURBgz. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Tame Impala Essentials with id 5s0oILbBofre0lYpqj7pMe. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export The Ataris Essentials with id 0v7gksQ6KLzE7c1HV2z3Mm. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export The Flaming Lips Essentials with id 7Lk3iNWydJKr0T7dX9zJjo. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Today's Indie Rock with id 6i0odq4TBebbZ6VnUGYeTf. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Untitled with id 4ReM9XfY4BhrBjTwdwenda. Encountered TypeError: Cannot read property 'forEach' of undefined.
Couldn't export Weezer Essentials with id 4HNskNnaS5atdPu2OWrLOR. Encountered TypeError: Cannot read property 'forEach' of undefined.

**Comment by ottopiramuthu** [comment]
spotify:playlist:16vLzPaeE4tV2y3dRykdoI crashes with error: `TypeError: song.track is null`

**Comment by chordsworldd** [comment]
Couldn't export New Music Nashville. Encountered TypeError: Cannot read property 'artists' of null

**Comment by Santinieve** [comment]
Hello, I was trying to export some playlists but on a couple of them i received: 
"Couldn't export "RS". Encountered TypeError: Cannot read properties of null (reading 'artists'). Please let us know.

I would like to know how I can fix it such that I can export the playlist. It would be useful if there was an option for "Skip song" perhaps? And for it to add a message of what song it skipped so the User is aware / OR: What song is causing the problem so that I can temporarily remove it

"

**Comment by Birblord2087** [comment]
Hiya, I'm experiencing this error:

"Couldn't export My Playlist #16. Encountered TypeError: Cannot read properties of undefined (reading 'forEach'). "

My playlist is https://open.spotify.com/playlist/0Y1UOzHss5Aq4nAr7Em4Ic and contains a number of local files. I'd be grateful if you could look into this, thank you!

**Comment by twigithub** [comment]
> Please post the URIs or links for playlists that just cause the button to spin forever, indicating a crash, in this thread. There are many ways things could potentially go wrong, so I foresee getting a lot of mileage out of this one.

Hi, 

These 4 playlists have an error, only in the website "exportify.net" though. On the site https://watsonbox.github.io/exportify I could download them. 
https://open.spotify.com/playlist/23NiBEEweVr0qrHeVQcAqa?si=ea0a2f3b379e457f
https://open.spotify.com/playlist/4u9kLNy8b5BtUNIfj46y2s?si=21af20b55135416a
https://open.spotify.com/playlist/4PQCx1gtjMy16vTuxLGYEe?si=7ecda828a2f14090
https://open.spotify.com/playlist/1gRXPhsufV2w6EAdrjuwQe?si=c350f6bb1bb346f7

"Sas Ipod" and "Flip" both have only local files, and the local files are actually not even on my device (pc). The other two playlists I am not sure about if they have some local files or no local files.
1e rang

Couldn't export 1e rang. Encountered TypeError: Cannot read properties of null (reading 'id'). Please let us know.
Couldn't export Check: alle Rangplaylist folder nummers 4 jan. Encountered TypeError: Cannot read properties of null (reading 'id'). 
Couldn't export Sas ipod. Encountered TypeError: Cannot read properties of undefined (reading 'forEach').
Couldn't export Flip. Encountered TypeError: Cannot read properties of undefined (reading 'forEach').

**Comment by TerremotoDePorta** [comment]
Hello. 

I get an error when export this playlist:
https://open.spotify.com/playlist/7Ibetk6QYkFBGP8JHaGp4p

Error is "Couldn't export Funbox Karaoke. Encountered TypeError: artist is null."

**Comment by Caveman-Trinity** [comment]
Couldn't export What Is the Meaning Of Life. Encountered TypeError: Cannot read properties of undefined (reading 'forEach'). Please [let us know](https://github.com/pavelkomarov/exportify/issues/10).

https://open.spotify.com/playlist/6hGHjnycbhFetS57W60k4f?si=4ab646032b55499f

**Comment by vynra** [comment]
Couldn't export misfits 2.0 with id 37i9dQZF1DXciq74vrQmM8. Encountered TypeError: Cannot read properties of null (reading 'artists').

https://open.spotify.com/playlist/37i9dQZF1DXciq74vrQmM8?si=293198ddc2c14fe6

**Comment by vynra** [comment]
Couldn't export I'm with the banned with id 37i9dQZF1DX4W90hOiKcOs. Encountered TypeError: Cannot read properties of null (reading 'artists').

https://open.spotify.com/playlist/37i9dQZF1DX4W90hOiKcOs?si=874a952d65254311

**Comment by theprof196** [comment]
Experiencing the same issue in August 2022 with Playlist 4kozevtq66HcRWf6Mlz4Vu

**Comment by AquaWo1f** [comment]
Couldn't export 😊✝️💖💙💔. Encountered TypeError: Cannot read properties of undefined (reading 'forEach')

https://open.spotify.com/playlist/2TXBnjbdS7o07f3mxKmZhg

**Comment by eitansch** [comment]
Hi, happened to me when trying to export playlist [mwfbnqunze7bplijy0tcbugo5](https://open.spotify.com/user/mwfbnqunze7bplijy0tcbugo5). I get:
`Couldn't export Hebrew Best. Encountered TypeError: Cannot read properties of null (reading 'id'). Please [let us know](https://github.com/pavelkomarov/exportify/issues/10).`
A suspicion is that it might contain UTF-8 or UTF-16 characters as this is a playlist with Hebrew songs which contain these characters in the song names.

**Comment by AquaWo1f** [comment]
It's okay.  I contacted the original creator, & he told me to try the
watsonbox version, and it works perfectly.  :)

**Comment by pavelkomarov** [comment]
I'm sorry I've been so missing, guys. This hasn't been a priority to fix, but it seems like there are some pretty common issues.

**Comment by Rami-Daoud** [comment]
> artist

I have same issue https://open.spotify.com/playlist/6RJnq7s597ar0dqIC8RwzK?si=4b71540db2954426

**Comment by Rami-Daoud** [comment]
> 

I have same issue https://open.spotify.com/playlist/6RJnq7s597ar0dqIC8RwzK?si=4b71540db2954426

**Comment by pavelkomarov** [comment]
Thanks. I sat down to work on this a couple weekends ago but only got as far as updating the repo to use github actions to deploy instead of travis.ci. I was able to successfully redeploy, but I redeployed the same exact version. Still have to add null checking to the javascript.

**Comment by flawedgun** [comment]
Getting an error: Couldn't export blank 192. Encountered TypeError: Cannot read properties of null (reading 'id'). Please let us know.

Playlist is: https://open.spotify.com/playlist/60fc9l7NZJqKvIucIhvxya

**Comment by ellwal** [comment]
Error: `Couldn't export blank 192. Encountered TypeError: Cannot read properties of null (reading 'id'). Please let us know.`
Playlist: https://open.spotify.com/playlist/0XwsaAOnntcJxjWXHu64ag

**Comment by paperlips** [comment]
Encountered TypeError: Cannot read properties of null (reading 'id').

Playlist https://open.spotify.com/playlist/19mgUlKqP2M6SOpaQWM6Fw?si=119bd5789ced4c55

**Comment by MLpranav** [comment]
Couldn't export Smartest Episodes of 2022 with id 37i9dQZF1DWVqY4F2OrvQx.

Encountered TypeError: Cannot read properties of null (reading 'artists').

**Comment by XBagon** [comment]
just printing out the `song.track`s which are `null`, helped fixing my playlist. Because the songs still have the `added_at` timestamps, I could determine which range of songs to remove, also I could add them right back and it still fixed my playlist. Then I just clicked export. So maybe the website could output the `added_at` and the indices of the failed songs or just console.error them to help out a bit.

**Comment by kamaulindhardt** [comment]
Hi authors to Exportify,

First of all, thank you for this fantastic technology. I love it. Unfortunately, I am encountering errors on a few of my playlists when exporting them.

- Couldn't export new south african house music 2023 with id 6QiyDqm7VTGRzLPpp1SNMj. Encountered TypeError: null is not an object (evaluating 'song.track.artists').
- Couldn't export 🔎 ⛩🦉Focus (Study Chill) . Encountered TypeError: null is not an object (evaluating 'song.track.artists')
- Couldn't export Chilletreet🍃🌲. Encountered TypeError: null is not an object (evaluating 'song.track.artists').
- Couldn't export Manu Fica with id 2KJdrbwqxj8ffEq1Fe1cAh. Encountered TypeError: null is not an object (evaluating 'artist.id')
- Couldn't export Spilled Ink with id 37i9dQZF1DWSTeI2WWFaia. Encountered TypeError: null is not an object (evaluating 'song.track.artists').
- Couldn't export Chilled R&B with id 37i9dQZF1DX2UgsUIg75Vg. Encountered TypeError: null is not an object (evaluating 'song.track.artists').

Other than those mentioned above the rest of my 299 playlists where successfully exported to csv. Thank you!

**Comment by johnsrude** [comment]
Couldn't export Classical New Releases with id 37i9dQZF1DWV0gynK7G6pD. Encountered TypeError: Cannot read properties of null (reading 'artists').

**Comment by RainOrigami** [comment]
https://open.spotify.com/playlist/17JJ2oOKjsfxa5G82Ikk3m
causes
`TypeError: Cannot read properties of null (reading 'id').`

**Comment by santiago-ls** [comment]
Hey @pavelkomarov, 

My wedding playlist is not exporting: https://open.spotify.com/playlist/7DOsODB9PVZM0nqljap49d?si=b807edfee41e4a0e

 ;'( 

I'm having this error: `TypeError: Cannot read properties of null (reading 'id').`

This is a great project! 
Thank you, 
Santiago

**Comment by hito2hito** [comment]
https://open.spotify.com/playlist/37i9dQZF1DX4OR8pnFkwhR
causes
Couldn't export RADAR: Early Noise . Encountered TypeError: Cannot read properties of null (reading 'artists'). 
😭

**Comment by hsuit** [comment]
I received the error `TypeError: null is not an object (evaluating 'artist.id')` and resolved it by removing two podcast episodes (for tracks that aren't on Spotify) from my playlist.

**Comment by WinterFollowsSpring** [comment]
https://open.spotify.com/playlist/0kFjwH3BRkcUoMwhs0NAaF crashes with `TypeError: song.track is null`

**Comment by ctindel** [comment]
https://open.spotify.com/playlist/780h58Q1YGBrAOGrSY8OoM crashes with Encountered TypeError: Cannot read properties of null (reading 'id').

**Comment by l3onDezzigner** [comment]
Couldn't export Novedades Viernes Colombia. Encountered TypeError: Cannot read properties of null (reading 'artists')

**Comment by l3onDezzigner** [comment]
Couldn't export Novedades Viernes Latinoamérica. Encountered TypeError: Cannot read properties of null (reading 'artists')

**Comment by l3onDezzigner** [comment]
Couldn't export Novedades Viernes Latinoamérica. Encountered TypeError: Cannot read properties of null (reading 'artists').

**Comment by Aaron668-5921** [comment]
I was encountering the error: “ Couldn't export Possible Export Trouble Songs. Encountered TypeError: null is not an object (evaluating 'artist.id').”. I exported successfully from the Watsonbox fork, and went hunting via Excel for problematic artist names. I was thinking it was probably a weird character or something, but eventually found, in this case, the trouble was a song uploaded as a podcast, Jen Titus’ “O Death”, where the artist name in the Watsonbox file was listed as “null”.

Removed it and all worked beautifully.

I hope this helps others.

**Comment by jlazarski** [comment]
Couldn't export The Rap Civil War of 2024 with id 1yT73f5xOzTXnSTeUN1yyO. Encountered TypeError: Cannot read properties of null (reading 'artists').

**Comment by pavelkomarov** [comment]
Hi guys, I'm back at this finally. Thanks for all your input over the *years* lol, wow. I've been watching the emails trickle in and realized a while ago the common theme is that I (and my code) assumed songs would *always* have tracks, artists, etc., and they almost always do, but it turns out that some times the database gods conspire against us. So the solution is to add safety checks in my `csvData()` function to handle those wrinkles. I'm working on it now.

**Comment by pavelkomarov** [comment]
It turns out this app might be the single most useful thing I've ever made in terms of number of users, so thanks for being here.
<img width="655" alt="Screenshot 2024-08-14 at 1 36 39 PM" src="https://github.com/user-attachments/assets/fd19252f-28d1-41cc-a47f-cfe0461ee8dc">

**Comment by pavelkomarov** [comment]
Okay, I just pushed. See [the commit](https://github.com/pavelkomarov/exportify/commit/07f47dbcd167cc26493ae55b828535aa4b6efb36) if you care for details. The new code is live! Let me know if you run in to more issues.

Special thanks to @PotatoPalooza for cluing me in to [the magic](https://stackoverflow.com/questions/61847231/question-mark-before-dot-in-javascript-react) of `?.`
