### ISSUE TITLE
Make table rows sortable by column

### ISSUE THREAD

**Issue by pavelkomarov** [pavelkomarov/exportify#11]
It would be nice if the table were more interactive so a user could click "Tracks" or "Name" and sort the rows in ascending/descending order.

[Here's a partial example](https://codepen.io/austinlyons/pen/YpmyJB).

**Comment by shape55** [comment]
Column sorting is actually a feature I requested not too long ago [here](https://github.com/watsonbox/exportify/issues/56#issuecomment-498328158), along with an additional column for "Last Updated" (or something to this effect, which I explained in that comment), as it would make the playlist backup process much easier for those who have a lot of them.

**Comment by pavelkomarov** [comment]
Yeah, I really want this, but I haven't figured out how to do it cleanly. Until such an approach becomes apparent to me, I won't jump.

**Comment by pavelkomarov** [comment]
Seems like this could be a fun challenge to figure out https://blog.logrocket.com/creating-react-sortable-table/

**Comment by pavelkomarov** [comment]
Done! https://github.com/pavelkomarov/exportify/commit/c33b7b384bb221977a1933b035f728343dd7d896

**Comment by pavelkomarov** [comment]
One possible pitfall of my method is that it only sorts the current batch of playlists in the table's data. The table maxes out at a length of 50, and you have to paginate over to the next 50 to see more. So if you expect to see a certain playlist upon sorting but don't, it may be in a different batch. I'd rather not confuse the user with unexpected behavior, but getting all playlists, sorting, then displaying the first 50 would be a bit silly. I could instead page through all the user's playlists and display them in a single massive table, no matter how many they've got. This would have the added benefit of letting them ctrl+F to find any particular playlist without having to paginate around. I might also then do away with pagination completely, shortening the code.
