### ISSUE TITLE
Release Dates:  Which era of music do I prefer?

### ISSUE THREAD

**Issue by iburunat** [pavelkomarov/exportify#15]
Congrats on this beautiful package! I merely wanted to point out that perhaps `release date` is not the most spot-on marker to answer the question of `which era of music do I prefer`. In my case, I have many classical music tracks, and you can see the problem here really clear :)

**Comment by pavelkomarov** [comment]
Tell music publishers that. Spotify uses their dates, and I use Spotify's dates, and there's no way to fix the mislabeled examples except case by case.
