### ISSUE TITLE
Couldn't export playlist. Encountered TypeError: Cannot read property 'artists' of null.

### ISSUE THREAD

**Issue by ethanmarston** [pavelkomarov/exportify#16]
I don't think it's local files because I just exported a playlist with 10000 songs and offline songs on it.

**Comment by pavelkomarov** [comment]
Can you link the playlist? I can follow it and try to download it myself and look at the terminal output/json coming back go see what's going on.

**Comment by pavelkomarov** [comment]
It sounds to me like there's a rogue song in there that doesn't have an artists field, so when I query for it, error.
