### ISSUE TITLE
Exporting list of albums

### ISSUE THREAD

**Issue by wwells35** [pavelkomarov/exportify#17]
Great tool! Is it possible to modify so that it also exports a full list of albums present in my library? Thanks

**Comment by pavelkomarov** [comment]
You can always read in all playlist CSVs, grab the column of albums from them all, and deduplicate. Easy in python. I can add a section to the Jupiter notebook if you're uncomfortable with code yourself.

**Comment by wwells35** [comment]
Thanks for the rapid reply. Deduplication is easy enough, but my problem is that the songs from saved albums ("Your Library / Albums) do not seem to appear in any playlist(s). So I would have to open each saved album, click to put it in a playlist, repeat again for every single album (there are a lot....), then download that playlist via your tool. I think this is because of a change in the app. Spotify Community says (as of mid-2019): "So the functionality of adding songs to your library has been changed in the last update. As you've discovered, tapping download or the heart button will no longer add an album to your Liked Songs."

**Comment by pavelkomarov** [comment]
I got rid of liked songs as a row in the table because you have to treat them so differently than a playlist and it was making the code ugly. Feel free to open a PR to add it back if you can find an elegant way. It's possible Spotify has improved something in the last year. Or easy hack others have used in the past: add your liked songs to a temporary playlist, export, and clean up

**Comment by wwells35** [comment]
Again from spotify community: "Unfortunately, as far as I am aware there is no way to select multiple albums to save to a playlist [like you can do with songs]." Therefore, you need to resort to a laborious, one by one process to add each album to a single, temporary playlist. :(
So my real question is whether your tool can be easily adapted to pull data on saved albums, as well as pulling data on saved playlists. But maybe that's a totally different tool.

**Comment by pavelkomarov** [comment]
Your liked songs can be found at a centralized place, selected at once, and put in a playlist all in one step.
