### ISSUE TITLE
Feature request: Ability to search through playlists

### ISSUE THREAD

**Issue by fsktom** [pavelkomarov/exportify#19]
I love exportify. But it's quite a bother to find the playlist you want if you have hundreds of them

![image](https://i.imgur.com/pem9UI0.png)

Could you add the ability to search through all your playlists? Or does this already exists and I'm just incompetent?

**Comment by pavel-aicradle** [comment]
I haven't implemented it, but recently @watsonbox has been greatly improving his version, and a search box is either already a feature or coming very soon. I might look in to stealing his code at some point.

**Comment by Filip-Tomasko** [comment]
Thanks for the quick answer. I'll be using his version then in the meantime ;p

**Comment by pavelkomarov** [comment]
I could alternatively put all the playlists in a massive table on a single page and let users ctrl+F. Does anyone like that idea? Get rid of pagination, potentially?

**Comment by pavelkomarov** [comment]
I've gone and done it. https://github.com/pavelkomarov/exportify/commit/35a1aedb8e75a317091183b52e9dfb7329fbb159 Adding a search box to filter table elements is also a possibility, but I think it's overkill, so I'm calling this one done.
