### ISSUE TITLE
Couldn't export 

### ISSUE THREAD

**Issue by danockgi** [pavelkomarov/exportify#27]
Please help with this error.  Thanks.

Couldn't export Liked 2022.09.27. Encountered TypeError: Cannot read properties of undefined (reading 'forEach')

**Comment by pavelkomarov** [comment]
Yeah, this probably belongs with #10

**Comment by pavelkomarov** [comment]
https://github.com/pavelkomarov/exportify/commit/07f47dbcd167cc26493ae55b828535aa4b6efb36
