### ISSUE TITLE
Exportify Fails to Export Spotify Playlist containing Local Files

### ISSUE THREAD

**Issue by alchokem** [pavelkomarov/exportify#28]
Exportify fails to export any playlist that has a local file in it. It is clear that Spotify manages local files differntly than those retrieved from its own servers. There is likely a property (perhaps Spotify Track ID) that doesn't exist for local files that only can be found in files retrieved from Spotify's servers which is the source of this error.

Example Error:  

Couldn't export Mark Morrison with id 218lExucf3LwPG9EomDHgr. Encountered TypeError: Cannot read properties of undefined (reading 'forEach').

I first reported this error back in June and have heard nothing.

UPDATE: I've discovered such a field which is missing in local files but exists in those on Spotify's servers,  The field is labeled 
               "ISRC" by Musicbackuper  in its JSON exports.

**Comment by pavelkomarov** [comment]
Awesome. Thanks for chasing this bug down so thoroughly. Sorry I'm missing. I don't get paid for this, was just a passion project a few years ago. But today I'm going to try to merge at least one fix.

**Comment by pavelkomarov** [comment]
I think this should be more thoroughly addressed by this https://github.com/pavelkomarov/exportify/commit/07f47dbcd167cc26493ae55b828535aa4b6efb36
