### ISSUE TITLE
add gear / config back on exportify.net?

### ISSUE THREAD

**Issue by gregsadetsky** [pavelkomarov/exportify#32]
hey,

thank you for running exportify.net!

compared to the [version from watsonbox](https://github.com/watsonbox/exportify), there doesn't seem to be a way to enable the "Include album data" option.

I was specifically looking for it because I wanted to export the label name for each song

would you consider adding the label field, or allowing "advanced" options to be set by the user?

thanks!

**Comment by pavelkomarov** [comment]
I pull data in several volleys in the `csvData` method of `sportily.js`. First all the tracks in a playlist, then all the artists for those songs, then specific audio features for the songs, then join. If label info is part of the track info, which [it looks like it is](https://developer.spotify.com/documentation/web-api/reference/get-several-tracks), then adding it to the output schema is as simple as nabbing it from those messages I'm already getting.

I'm unlikely to make this change myself, but I'd be happy to guide you if you'd like to submit a PR.

**Comment by pavelkomarov** [comment]
Adding a whole menu where users choose which columns they'd like in the output is an option too, but it's a lot harder to achieve, so I'm even less likely to spend time on it.

**Comment by pavelkomarov** [comment]
Do you still want a record label column? What other columns would you specifically like?

It looks like Spotify has "[Audio Analysis](https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis)" now in addition to the "[Audio Features](https://developer.spotify.com/documentation/web-api/reference/get-audio-features)" I was using. There are basically *a lot* of possible things we could pull out here, and I think exhaustively getting them all is overkill, but I do want to get you the info and features you think you need.

**Comment by gregsadetsky** [comment]
hey, thanks for the follow up! the record label would be great to have

**Comment by pavelkomarov** [comment]
Label info is only in Album JSON, not in Track JSON. That complicates things. It would indeed be a separate volley of traffic, similar to how I grab Artists to get genres from them. Doable and not so bad if you follow the code structure in `csvData`.

**Comment by pavelkomarov** [comment]
Decided the scope of this one is not the gear icon and field-selectability for users; it's merely to give you the record labels you wanted. It's live.
