### ISSUE TITLE
Error: 'float' object has no attribute 'split' when plotting Artist Bar Chart

### ISSUE THREAD

**Issue by MaltheHoey** [pavelkomarov/exportify#39]
I'm experiencing some issues upon plotting the artist bar chart with Exportify. The first script runs without issue, but it seems that there's some error in the Artist column, which I suspect could be empty cells in the CSV, but I'm hoping that the code can run regardless? Any help would be much appreciated

**Comment by pavelkomarov** [comment]
What was the error, specifically? I'm guessing somewhere in

```python
for i,song in data.iterrows():
	for musician in song['Artist Name(s)'].split(','):
		artists[musician] += 1
```

you're getting missing artists, so that when you attempt to `split()` it doesn't work?

**Comment by pavelkomarov** [comment]
Similar to https://github.com/pavelkomarov/exportify/issues/41, I've added a check:

```python
for i,song in data.iterrows():
    if isinstance(song['Artist Name(s)'], str):
    	for musician in song['Artist Name(s)'].split(','):
    		artists[musician] += 1
```
