### ISSUE TITLE
Error in Cell 16 (Release Dates)

### ISSUE THREAD

**Issue by x1-foundation** [pavelkomarov/exportify#41]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 3
      1 years = defaultdict(int)
      2 for i,song in data.iterrows():
----> 3     years[song['Release Date'][:4]] += 1
      5 years = pandas.DataFrame(years.items(), columns=['Year', 'Num Songs']
      6                           ).sort_values('Year')
      8 pyplot.figure(figsize=(10, 6))

TypeError: 'float' object is not subscriptable

**Comment by pavelkomarov** [comment]
Okay, not a pandas issue; this is a missing data issue. I've added a check:

```python
for i,song in data.iterrows():
    if isinstance(song['Release Date'], str): # somebody found a NaN release date!
        years[song['Release Date'][:4]] += 1
```
