### ISSUE TITLE
Error in "fit that gamma to the time-reversed data."

### ISSUE THREAD

**Issue by x1-foundation** [pavelkomarov/exportify#42]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[21], line 6
      3 youngest = int(years['Year'].values[-1])
      4 missing_years = [str(x) for x in range(eldest+1, youngest) if
      5                  str(x) not in years['Year'].values]
----> 6 ago = years.append(pandas.DataFrame.from_dict(
      7     {'Year': missing_years, 'Num Songs': [0 for x in range(len(missing_years))]})
      8                   ).sort_values('Year', ascending=False).reset_index(drop=True)
     10 y = []
     11 for i in range(ago.shape[0]):

File /srv/conda/envs/notebook/lib/python3.10/site-packages/pandas/core/generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'

Your code is trying to fill in missing years in the dataset and then fit a gamma distribution to the number of songs released each year. However, there are a few issues that need to be addressed:

When appending missing years, ensure the data types match for concatenation.
The gamma distribution fitting might need an initial guess for the shape parameter, which can be provided as an argument to the fit method.

**Comment by pavelkomarov** [comment]
Yep, they went and changed the API under me. Coding a fix now.

**Comment by pavelkomarov** [comment]
https://github.com/pavelkomarov/exportify/commit/bcc2c7a63ce2d37d32aecde4d0c270020b25ef39
