### ISSUE TITLE
Error in "Musical Features"

### ISSUE THREAD

**Issue by x1-foundation** [pavelkomarov/exportify#43]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[28], line 15
     12     pyplot.title(category)
     14     pyplot.subplot(9, 2, i*2+2)
---> 15     pyplot.imshow(pyplot.imread('https://developer.spotify.com/assets/audio/'+
     16                                 category.lower()+'.png'))
     17     pyplot.axis('off')  
     19 pyplot.tight_layout(h_pad=2)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/matplotlib/pyplot.py:2195, in imread(fname, format)
   2193 @_copy_docstring_and_deprecators(matplotlib.image.imread)
   2194 def imread(fname, format=None):
-> 2195     return matplotlib.image.imread(fname, format)

File /srv/conda/envs/notebook/lib/python3.10/site-packages/matplotlib/image.py:1558, in imread(fname, format)
   1554 img_open = (
   1555     PIL.PngImagePlugin.PngImageFile if ext == 'png' else PIL.Image.open)
   1556 if isinstance(fname, str) and len(parse.urlparse(fname).scheme) > 1:
   1557     # Pillow doesn't handle URLs directly.
-> 1558     raise ValueError(
   1559         "Please open the URL for reading and pass the "
   1560         "result to Pillow, e.g. with "
   1561         "``np.array(PIL.Image.open(urllib.request.urlopen(url)))``."
   1562         )
   1563 with img_open(fname) as image:
   1564     return (_pil_png_to_float_array(image)
   1565             if isinstance(image, PIL.PngImagePlugin.PngImageFile) else
   1566             pil_to_array(image))

ValueError: Please open the URL for reading and pass the result to Pillow, e.g. with ``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.

**Comment by pavelkomarov** [comment]
Okay, I see what's going on. I was pulling in histograms Spotify provided on a particular web page, but that page doesn't exist anymore. It looks like the modern equivalent of that page just doesn't have histograms. :( https://developer.spotify.com/documentation/web-api/reference/get-audio-features

**Comment by pavelkomarov** [comment]
Looks like they now have "audio analysis" in addition to "audio features", which is a bit more in-depth. Might be fun to play with, but I'm not gonna worry about confidence values and such for this https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis
