### ISSUE TITLE
Couldn't export CALDAS V. Encountered TypeError: Cannot read properties of null (reading 'id').

### ISSUE THREAD

**Issue by rodrigocbraga10** [pavelkomarov/exportify#46]
While attempting to export a file named "CALDAS V", I encountered the following error:
_TypeError: Cannot read properties of null (reading 'id')_

Expected Behavior:
The file should export without any errors.

Actual Behavior:
The export process fails and the following error message is displayed: TypeError: Cannot read properties of null (reading 'id').

Additional Information:
> The error occurs consistently with the same file.

Thank you for your assistance in resolving this issue.

**Comment by pavelkomarov** [comment]
I believe this is fixed with [this commit](https://github.com/pavelkomarov/exportify/commit/07f47dbcd167cc26493ae55b828535aa4b6efb36)
