### ISSUE TITLE
Display playlist images instead of ♫ icons

### ISSUE THREAD

**Issue by pavelkomarov** [pavelkomarov/exportify#49]
It is possible to fetch playlist images. It wouldn't be that hard to grab them around the same time the code is grabbing the list of playlists and display them in the table.

**Comment by ChinoUkaegbu** [comment]
Also unrelated but in the exportify.js comments I see that you pointed out `// createElement is a legacy API but it's unclear what the recommendation is to modernize`. I believe using JSX would be the alternative (would be a lot more readable as well imo)

**Comment by pavelkomarov** [comment]
Wow. It works spectacularly, and it's like a two-line change. Good work!

**Comment by ChinoUkaegbu** [comment]
> Whoa! A wild `contributor` has appeared! I'll take a look at the PR. Thank you.
> 
> And yes, I think JSX is the way. I've got #48 for this.

will check that out!
