### ISSUE TITLE
I created exportify-cli

### ISSUE THREAD

**Issue by donmerendolo** [pavelkomarov/exportify#55]
Hi! I wanted to let you know that I (well, ChatGPT) built a Python program called [exportify-cli](https://github.com/donmerendolo/exportify-cli), inspired by your repository, to back up Spotify playlists directly from the terminal (I wanted to automate the process). Just wanted to say thanks! 😃

**Comment by pavelkomarov** [comment]
Glad Chat could ingest my and others’ code lol.
