### ISSUE TITLE
Persistent HTTP 500 Error on Playlist Loading

### ISSUE THREAD

**Issue by salvioma** [pavelkomarov/exportify#61]
Hi,

Thank you for addressing the previous issue, but I’m still encountering a problem. The web interface is stuck on "http://localhost:8000/#playlists" with an HTTP 500 error. The page keeps loading without displaying playlists.

Error Details:
- Issue: HTTP 500 response when trying to load playlists.
- Impact: Unable to access the playlists.
- Reproduction: Occurs consistently when accessing the playlists page.

Could you please help resolve this issue? Thanks!

**Comment by pavelkomarov** [comment]
Localhost? So you cloned and ran `python3 -m http.server` yourself? It's also hosted at [exportify.net](https://exportify.net). Does it also not work there?

If there's a 500 response when trying to load your playlists, then maybe Spotify can't fetch all your playlists for some reason. I'm now loading all user playlists on one screen, so I need them all to be findable and returnable by Spotify--which they should be, but the Laws of Large Systems could goof that up. How many playlists do you have total? And can you see them all through Spotify's website and in their app?

**Comment by salvioma** [comment]
Hello, Pavelkomarov,

Until recently, I had always used exportify.net for convenience. However, as the issue persisted, I decided to download the code and run it locally in an attempt to resolve it. After making some adjustments, such as replacing the deprecated sklearn package, the error still occurs.

Given that I have only 5-10 playlists, I doubt the issue is related to quantity. It may be due to an invalid token from the Spotify API, as I’ve encountered similar errors with other services relying on this API.

I would greatly appreciate your help in investigating this, and if necessary, we could also consider contacting Spotify.

Thank you for providing this valuable tool. It has been incredibly helpful, particularly for organizing playlists based on the detailed genre tags, which allow me to curate lists with precision and consistency.

I look forward to a resolution. Thank you again for your time and attention.

**Comment by pavelkomarov** [comment]
A 500 response indicates there is an issue on Spotify's side. Does the issue happen when you try to log in or when you try to load playlists? Those things happen one after the other, so it's difficult to tell without looking at the actual traffic. What was the last request sent to the server, to which it returns HTTP 500?

**Comment by salvioma** [comment]
I can access my playlists without any issues directly from https://open.spotify.com/playlist/, so it seems the problem is not related to my Spotify account, but rather how Exportify is interacting with the Spotify API in my case.

When I have the chance, I'll check the developer console in my browser to capture the last request before the HTTP 500 error. I’ll get back to you with more information on the failed request (endpoint and response) for further investigation.

Thank you for your assistance.

**Comment by pavelkomarov** [comment]
Do you have the same trouble if you use the version hosted at watsonbox.io/exportify?

**Comment by salvioma** [comment]
**Subject: Issue with /v1/me/tracks Endpoint Due to Large Liked Songs Playlist**

Hi Pavel,
Thanks for your help with previous issues. I’ve been investigating further into the problem I’m facing, and wanted to share what I’ve discovered so far in hopes that you might offer some additional guidance.

It seems the HTTP 502 error I encounter when trying to load data from the **/v1/me/tracks** endpoint isn't related to the API functionality or the Access Token, as I can access other endpoints like /v1/me/playlists and /v1/me/albums without any issues. After deeper analysis, I believe the problem lies with my **Liked Songs playlist**.

I currently have over 57,000 songs saved in Liked Songs, and it seems the server struggles to process this volume, which likely results in the 502 error. Interestingly, when I had around 50,000 songs a month ago, Exportify worked just fine. This leads me to wonder if a recent change or update could be affecting the handling of large song lists.

Luckily, I’ve been able to use a secondary account with far fewer saved songs to successfully export the playlists I need, but I’d prefer to keep using my primary account.

### My main questions are:
- Is there any way to modify Exportify to skip the Liked Songs playlist during export, so I can use my main account without hitting this issue?
- Do you think this problem could be tied to a recent update in the Spotify API? I was able to export my data when I had 50,000 songs, but now with 57,000, I’m encountering the error.

Best regards,

**Comment by pavelkomarov** [comment]
When does the 502 error occur? When building out your list of playlists, I fetch a single song's metadata from your liked songs, because the return message contains the total number of liked songs. I can then use that info to create an identical data structure to that which comes back for playlists, which allows me to effectively treat liked songs *as* a playlist.

The web API definitely shouldn't fail just because that number is 57k as opposed to 50k. Report this bug to Spotify on their forums.

You can see where I form the list of playlists in the code, exportify.js. I query the liked songs endpoint near the top, which sounds like it must be the query that precipitates a server failure.
