### ISSUE TITLE
Encountered TypeError (reading 'slice')

### ISSUE THREAD

**Issue by l3onDezzigner** [pavelkomarov/exportify#66]
Couldn't export Novedades Viernes Colombia. Encountered TypeError: Cannot read properties of undefined (reading 'slice')
TypeError: Cannot read properties of undefined (reading 'slice') at https://exportify.net/exportify.js:264:33 at Array.forEach () at https://exportify.net/exportify.js:262:9 at async Object.export (https://exportify.net/exportify.js:143:14)

**Comment by pavelkomarov** [comment]
Does it work now? https://github.com/pavelkomarov/exportify/commit/dce30da2e41cbb5b9660069fff8edb808d5b4fec

**Comment by pavelkomarov** [comment]
Whoop. I just realized another change I made today wasn't quite right and was affecting this. https://github.com/pavelkomarov/exportify/commit/8f37f60e40a0de3917f41e2fe6bb4a140af5d589
