### ISSUE TITLE
Corrupted CSV file when exporting any playlist on website

### ISSUE THREAD

**Issue by devilapps** [pavelkomarov/exportify#68]
I tried more than 20 times in different browser but issue persist.says it has 0 file when exporting to YouTube.
upload CSV file and screenshot on gofile check and fix it asap.
https://gofile.io/d/rXRBva

**Comment by pavelkomarov** [comment]
Exportify only allows you to export a csv file. I do not control the import function on other sites. What are you trying to do, exactly?
