### ISSUE TITLE
Left/right arrows not working in Firefox

### ISSUE THREAD

**Issue by shape55** [pavelkomarov/exportify#7]
In Firefox, after loading my playlists, the arrows above the "Export All" button to go to the next page are not responding when clicked.

**Comment by pavelkomarov** [comment]
This should be fixed now. [changes](https://github.com/pavelkomarov/exportify/commit/92d325ec6403a06550b35dc3765b4bfddfe433e5)

**Comment by shape55** [comment]
Yup, I tested it again and it works as expected - thanks!
