### ISSUE TITLE
"Get Started" button not working in Chrome

### ISSUE THREAD

**Issue by shape55** [pavelkomarov/exportify#8]
In Chrome, the "Get Started" button doesn't respond when clicked.  I've noticed this same problem with buttons on other Spotify web backup apps in Chrome.

**Comment by pavelkomarov** [comment]
I am running the most recent Chrome in Linux mint and am able to log in without a problem. Can you elaborate about your situation?

**Comment by shape55** [comment]
Well, it's an older version of Mac Chrome but the latest one for my OS.  None of the other Exportify variations I've tried have this issue w/ the "Get Started" button though.  It works fine on this version of Chrome using these links:

https://rawgit.com/watsonbox/exportify/master/exportify.html

https://cdn.rawgit.com/martenjacobs/exportify/29170b821a1c8ca51d7dbb0eb77bfc0e89746255/exportify.html

https://rawgit.com/delight-im/exportify/master/exportify.html

**Comment by pavelkomarov** [comment]
Possibly a browser that old doesn't support `fetch` or `async` or some other syntax I've used. Open the browser's terminal and see if it prints some kind of error message.

If it actually is that, I have no interest in making this backwards compatible with every browser. JavaScript has evolved significantly, and everyone seems to have fallen in line behind a new standard, and that's what I'm aiming at. Conditionals to handle special cases like that tend to complicate the code.

**Comment by shape55** [comment]
Ok, this is what shows up in the browser Console:

x Uncaught SyntaxError: Unexpected identifier    exportify.js:24 
x Uncaught ReferenceError: utils is not defined    app.html:37 
 onclick @ app.html:37

Unfortunately, I have no coding knowledge so I can be of any help in that matter :(

**Comment by pavelkomarov** [comment]
No coding knowledge, yet has had a github account for years. lol. Yeah, line 24 has an async on it, which was added to the JavaScript standard a few years ago. Your browser is likely just out of date. Imma close this one as a wontfix.

**Comment by shape55** [comment]
Ha, I'm sure that's a somewhat rare combo :)  I always make sure to report bugs and come to ask questions as well.

Ok, no prob.
